# Generated by Django 5.0.14 on 2025-05-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='dt_nascimeno',
            new_name='dt_nascimento',
        ),
    ]
