# Generated by Django 5.0.14 on 2025-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_dt_nascimeno_usuario_dt_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ni',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
