# Generated by Django 5.0.14 on 2025-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dt_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
